name: p03_lopez_salido_stein_zakrajsek_2017_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  # Core dependencies
  - doit==0.36.0
  - ipython
  - matplotlib==3.9.2
  - numpy==1.26.4
  - openpyxl==3.1.5
  - pandas-datareader==0.10.0
  - pandas==2.2.3
  - plotly==5.24.1
  - pyarrow
  - cruft
  - ruff
  - pytest==8.3.3
  - python-decouple==3.8
  - python-dotenv==1.0.1
  - requests==2.32.3
  - scipy==1.12.0
  - statsmodels==0.14.4
  - xlrd==2.0.1

  # Jupyter dependencies
  - jupyter
  - jupyterlab
  - jupytext
  - notebook

  - pip
  - pip:
      - chartbook[all]
      - wrds>=3.2.0
