name: p03_lopez_salido_stein_zakrajsek_2017_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  # Core dependencies
  - doit==0.37.0
  - ipython==9.8.0
  - matplotlib==3.10.9
  - numpy==2.2.6
  - openpyxl==3.1.5
  - pandas-datareader==0.11.1
  - pandas==2.2.3
  - plotly==6.9.0
  - pyarrow
  - pytest==9.1.1
  - python-decouple==3.8
  - requests==2.34.2
  - scipy==1.18.0
  - statsmodels==0.14.6
  - xlrd==2.0.2
  - ruff
  - cruft

  # Jupyter dependencies
  - jupyter
  - jupyterlab
  - jupytext
  - notebook

  - pip
  - pip:
      - chartbook[all]
      - wrds>=3.5.0
